export { default as Header } from "./header"
export { default as Layout } from "./layout"
export { default as SEO } from "./seo"
export { default as Jumbo } from "./jumbo"
export { default as Suggestions } from "./suggestions"
export { default as SuggestionDetail } from "./suggestionDetail"
